import { networkInterfaces } from "node:os";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");

function isPrivateIpv4(ip) {
  if (ip.startsWith("10.")) {
    return true;
  }

  if (ip.startsWith("192.168.")) {
    return true;
  }

  if (ip.startsWith("172.")) {
    const secondOctet = Number(ip.split(".")[1]);
    return Number.isFinite(secondOctet) && secondOctet >= 16 && secondOctet <= 31;
  }

  return false;
}

function detectLanIp() {
  const interfaces = networkInterfaces();
  const candidates = [];

  for (const [name, addresses] of Object.entries(interfaces)) {
    if (!addresses) {
      continue;
    }

    for (const addressInfo of addresses) {
      if (addressInfo.family !== "IPv4" || addressInfo.internal) {
        continue;
      }

      const ip = addressInfo.address;
      let score = 0;

      if (name === "en0") {
        score += 100;
      }

      if (isPrivateIpv4(ip)) {
        score += 10;
      }

      candidates.push({ ip, score });
    }
  }

  if (candidates.length === 0) {
    return null;
  }

  candidates.sort((a, b) => b.score - a.score);
  return candidates[0].ip;
}

function parseIpArg() {
  const args = process.argv.slice(2);
  const ipIndex = args.findIndex((arg) => arg === "--ip");
  if (ipIndex < 0) {
    return null;
  }

  const providedIp = args[ipIndex + 1]?.trim();
  return providedIp || null;
}

async function writeEnvFile(targetPath, content) {
  await mkdir(path.dirname(targetPath), { recursive: true });
  await writeFile(targetPath, content, "utf8");
}

async function main() {
  const ip = parseIpArg() ?? detectLanIp();
  if (!ip) {
    console.error("[lan:sync] LAN IPv4 주소를 찾지 못했습니다. --ip 옵션으로 직접 입력하세요.");
    process.exit(1);
  }

  const apiOrigin = `http://${ip}:4000`;
  const webUiOrigin = `http://${ip}:5173`;
  const kakaoRedirectUri = `${apiOrigin}/auth/kakao/callback`;

  const mobileEnvPath = path.join(repoRoot, "apps/mobile/.env.local");
  const apiEnvPath = path.join(repoRoot, "apps/api/.env.local");

  const mobileEnvContent = `EXPO_PUBLIC_API_ORIGIN=${apiOrigin}\n`;
  const apiEnvContent = [
    "# Auto-generated by scripts/sync-lan-env.mjs",
    `KAKAO_REDIRECT_URI=${kakaoRedirectUri}`,
    `WEB_UI_ORIGIN=${webUiOrigin}`,
    "",
  ].join("\n");

  await Promise.all([
    writeEnvFile(mobileEnvPath, mobileEnvContent),
    writeEnvFile(apiEnvPath, apiEnvContent),
  ]);

  console.log(`[lan:sync] LAN IP: ${ip}`);
  console.log(`[lan:sync] apps/mobile/.env.local -> EXPO_PUBLIC_API_ORIGIN=${apiOrigin}`);
  console.log(`[lan:sync] apps/api/.env.local -> KAKAO_REDIRECT_URI=${kakaoRedirectUri}`);
  console.log(`[lan:sync] apps/api/.env.local -> WEB_UI_ORIGIN=${webUiOrigin}`);
}

main().catch((error) => {
  console.error("[lan:sync] 동기화 실패", error);
  process.exit(1);
});
